// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/metadata.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{0}
}

type Mock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Producers     []string               `protobuf:"bytes,1,rep,name=producers,proto3" json:"producers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mock) Reset() {
	*x = Mock{}
	mi := &file_proto_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mock) ProtoMessage() {}

func (x *Mock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mock.ProtoReflect.Descriptor instead.
func (*Mock) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *Mock) GetProducers() []string {
	if x != nil {
		return x.Producers
	}
	return nil
}

type TV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []string               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	Showrunners   []string               `protobuf:"bytes,2,rep,name=showrunners,proto3" json:"showrunners,omitempty"`
	IsAnime       bool                   `protobuf:"varint,3,opt,name=is_anime,json=isAnime,proto3" json:"is_anime,omitempty"`
	IsAnimated    bool                   `protobuf:"varint,4,opt,name=is_animated,json=isAnimated,proto3" json:"is_animated,omitempty"`
	Studios       []string               `protobuf:"bytes,5,rep,name=studios,proto3" json:"studios,omitempty"`
	Networks      []string               `protobuf:"bytes,6,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TV) Reset() {
	*x = TV{}
	mi := &file_proto_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TV) ProtoMessage() {}

func (x *TV) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TV.ProtoReflect.Descriptor instead.
func (*TV) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *TV) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *TV) GetShowrunners() []string {
	if x != nil {
		return x.Showrunners
	}
	return nil
}

func (x *TV) GetIsAnime() bool {
	if x != nil {
		return x.IsAnime
	}
	return false
}

func (x *TV) GetIsAnimated() bool {
	if x != nil {
		return x.IsAnimated
	}
	return false
}

func (x *TV) GetStudios() []string {
	if x != nil {
		return x.Studios
	}
	return nil
}

func (x *TV) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []string               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	Authors       []string               `protobuf:"bytes,2,rep,name=authors,proto3" json:"authors,omitempty"`
	Illustrators  []string               `protobuf:"bytes,3,rep,name=illustrators,proto3" json:"illustrators,omitempty"`
	IsIllustrated bool                   `protobuf:"varint,4,opt,name=is_illustrated,json=isIllustrated,proto3" json:"is_illustrated,omitempty"`
	IsManga       bool                   `protobuf:"varint,5,opt,name=is_manga,json=isManga,proto3" json:"is_manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_proto_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *Book) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Book) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Book) GetIllustrators() []string {
	if x != nil {
		return x.Illustrators
	}
	return nil
}

func (x *Book) GetIsIllustrated() bool {
	if x != nil {
		return x.IsIllustrated
	}
	return false
}

func (x *Book) GetIsManga() bool {
	if x != nil {
		return x.IsManga
	}
	return false
}

var File_proto_metadata_proto protoreflect.FileDescriptor

const file_proto_metadata_proto_rawDesc = "" +
	"\n" +
	"\x14proto/metadata.proto\x12\x12bene.atom.metadata\"\a\n" +
	"\x05Empty\"$\n" +
	"\x04Mock\x12\x1c\n" +
	"\tproducers\x18\x01 \x03(\tR\tproducers\"\xb0\x01\n" +
	"\x02TV\x12\x16\n" +
	"\x06genres\x18\x01 \x03(\tR\x06genres\x12 \n" +
	"\vshowrunners\x18\x02 \x03(\tR\vshowrunners\x12\x19\n" +
	"\bis_anime\x18\x03 \x01(\bR\aisAnime\x12\x1f\n" +
	"\vis_animated\x18\x04 \x01(\bR\n" +
	"isAnimated\x12\x18\n" +
	"\astudios\x18\x05 \x03(\tR\astudios\x12\x1a\n" +
	"\bnetworks\x18\x06 \x03(\tR\bnetworks\"\x9e\x01\n" +
	"\x04Book\x12\x16\n" +
	"\x06genres\x18\x01 \x03(\tR\x06genres\x12\x18\n" +
	"\aauthors\x18\x02 \x03(\tR\aauthors\x12\"\n" +
	"\fillustrators\x18\x03 \x03(\tR\fillustrators\x12%\n" +
	"\x0eis_illustrated\x18\x04 \x01(\bR\risIllustrated\x12\x19\n" +
	"\bis_manga\x18\x05 \x01(\bR\aisMangaB7Z5github.com/minkezhang/bene-api/proto/go/atom/metadatab\x06proto3"

var (
	file_proto_metadata_proto_rawDescOnce sync.Once
	file_proto_metadata_proto_rawDescData []byte
)

func file_proto_metadata_proto_rawDescGZIP() []byte {
	file_proto_metadata_proto_rawDescOnce.Do(func() {
		file_proto_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metadata_proto_rawDesc), len(file_proto_metadata_proto_rawDesc)))
	})
	return file_proto_metadata_proto_rawDescData
}

var file_proto_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_metadata_proto_goTypes = []any{
	(*Empty)(nil), // 0: bene.atom.metadata.Empty
	(*Mock)(nil),  // 1: bene.atom.metadata.Mock
	(*TV)(nil),    // 2: bene.atom.metadata.TV
	(*Book)(nil),  // 3: bene.atom.metadata.Book
}
var file_proto_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_metadata_proto_init() }
func file_proto_metadata_proto_init() {
	if File_proto_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metadata_proto_rawDesc), len(file_proto_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_metadata_proto_goTypes,
		DependencyIndexes: file_proto_metadata_proto_depIdxs,
		MessageInfos:      file_proto_metadata_proto_msgTypes,
	}.Build()
	File_proto_metadata_proto = out.File
	file_proto_metadata_proto_goTypes = nil
	file_proto_metadata_proto_depIdxs = nil
}
