// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/metadata.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{0}
}

type Mock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Producers     []string               `protobuf:"bytes,1,rep,name=producers,proto3" json:"producers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mock) Reset() {
	*x = Mock{}
	mi := &file_proto_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mock) ProtoMessage() {}

func (x *Mock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mock.ProtoReflect.Descriptor instead.
func (*Mock) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *Mock) GetProducers() []string {
	if x != nil {
		return x.Producers
	}
	return nil
}

type TV struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Seasons          []int32                `protobuf:"varint,1,rep,packed,name=seasons,proto3" json:"seasons,omitempty"`
	Genres           string                 `protobuf:"bytes,2,opt,name=genres,proto3" json:"genres,omitempty"`
	Showrunners      string                 `protobuf:"bytes,3,opt,name=showrunners,proto3" json:"showrunners,omitempty"`
	IsAnimated       string                 `protobuf:"bytes,4,opt,name=is_animated,json=isAnimated,proto3" json:"is_animated,omitempty"`
	Directors        []string               `protobuf:"bytes,5,rep,name=directors,proto3" json:"directors,omitempty"`
	Writers          []string               `protobuf:"bytes,6,rep,name=writers,proto3" json:"writers,omitempty"`
	Cinematography   []string               `protobuf:"bytes,7,rep,name=cinematography,proto3" json:"cinematography,omitempty"`
	Composers        []string               `protobuf:"bytes,8,rep,name=composers,proto3" json:"composers,omitempty"`
	Starring         []string               `protobuf:"bytes,9,rep,name=starring,proto3" json:"starring,omitempty"`
	AnimationStudios []string               `protobuf:"bytes,10,rep,name=animation_studios,json=animationStudios,proto3" json:"animation_studios,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TV) Reset() {
	*x = TV{}
	mi := &file_proto_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TV) ProtoMessage() {}

func (x *TV) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TV.ProtoReflect.Descriptor instead.
func (*TV) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *TV) GetSeasons() []int32 {
	if x != nil {
		return x.Seasons
	}
	return nil
}

func (x *TV) GetGenres() string {
	if x != nil {
		return x.Genres
	}
	return ""
}

func (x *TV) GetShowrunners() string {
	if x != nil {
		return x.Showrunners
	}
	return ""
}

func (x *TV) GetIsAnimated() string {
	if x != nil {
		return x.IsAnimated
	}
	return ""
}

func (x *TV) GetDirectors() []string {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *TV) GetWriters() []string {
	if x != nil {
		return x.Writers
	}
	return nil
}

func (x *TV) GetCinematography() []string {
	if x != nil {
		return x.Cinematography
	}
	return nil
}

func (x *TV) GetComposers() []string {
	if x != nil {
		return x.Composers
	}
	return nil
}

func (x *TV) GetStarring() []string {
	if x != nil {
		return x.Starring
	}
	return nil
}

func (x *TV) GetAnimationStudios() []string {
	if x != nil {
		return x.AnimationStudios
	}
	return nil
}

var File_proto_metadata_proto protoreflect.FileDescriptor

const file_proto_metadata_proto_rawDesc = "" +
	"\n" +
	"\x14proto/metadata.proto\x12\x12bene.atom.metadata\"\a\n" +
	"\x05Empty\"$\n" +
	"\x04Mock\x12\x1c\n" +
	"\tproducers\x18\x01 \x03(\tR\tproducers\"\xc0\x02\n" +
	"\x02TV\x12\x18\n" +
	"\aseasons\x18\x01 \x03(\x05R\aseasons\x12\x16\n" +
	"\x06genres\x18\x02 \x01(\tR\x06genres\x12 \n" +
	"\vshowrunners\x18\x03 \x01(\tR\vshowrunners\x12\x1f\n" +
	"\vis_animated\x18\x04 \x01(\tR\n" +
	"isAnimated\x12\x1c\n" +
	"\tdirectors\x18\x05 \x03(\tR\tdirectors\x12\x18\n" +
	"\awriters\x18\x06 \x03(\tR\awriters\x12&\n" +
	"\x0ecinematography\x18\a \x03(\tR\x0ecinematography\x12\x1c\n" +
	"\tcomposers\x18\b \x03(\tR\tcomposers\x12\x1a\n" +
	"\bstarring\x18\t \x03(\tR\bstarring\x12+\n" +
	"\x11animation_studios\x18\n" +
	" \x03(\tR\x10animationStudiosB7Z5github.com/minkezhang/bene-api/proto/go/atom/metadatab\x06proto3"

var (
	file_proto_metadata_proto_rawDescOnce sync.Once
	file_proto_metadata_proto_rawDescData []byte
)

func file_proto_metadata_proto_rawDescGZIP() []byte {
	file_proto_metadata_proto_rawDescOnce.Do(func() {
		file_proto_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metadata_proto_rawDesc), len(file_proto_metadata_proto_rawDesc)))
	})
	return file_proto_metadata_proto_rawDescData
}

var file_proto_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_metadata_proto_goTypes = []any{
	(*Empty)(nil), // 0: bene.atom.metadata.Empty
	(*Mock)(nil),  // 1: bene.atom.metadata.Mock
	(*TV)(nil),    // 2: bene.atom.metadata.TV
}
var file_proto_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_metadata_proto_init() }
func file_proto_metadata_proto_init() {
	if File_proto_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metadata_proto_rawDesc), len(file_proto_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_metadata_proto_goTypes,
		DependencyIndexes: file_proto_metadata_proto_depIdxs,
		MessageInfos:      file_proto_metadata_proto_msgTypes,
	}.Build()
	File_proto_metadata_proto = out.File
	file_proto_metadata_proto_goTypes = nil
	file_proto_metadata_proto_depIdxs = nil
}
