// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/data.proto

package data

import (
	api "github.com/minkezhang/bene-api/proto/go/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_NODE_UNKNOWN  NodeType = 0
	NodeType_NODE_SEMANTIC NodeType = 1
	NodeType_NODE_TV       NodeType = 2
	NodeType_NODE_MOVIE    NodeType = 3
	NodeType_NODE_VIDEO    NodeType = 4
	NodeType_NODE_PAPER    NodeType = 5
	NodeType_NODE_BOOK     NodeType = 6
	NodeType_NODE_NOVELLA  NodeType = 7 // e.g. short story or poem
	// NODE_FANFICTION = 16;
	NodeType_NODE_GAME    NodeType = 8
	NodeType_NODE_ALBUM   NodeType = 9
	NodeType_NODE_SONG    NodeType = 10
	NodeType_NODE_PODCAST NodeType = 11
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0:  "NODE_UNKNOWN",
		1:  "NODE_SEMANTIC",
		2:  "NODE_TV",
		3:  "NODE_MOVIE",
		4:  "NODE_VIDEO",
		5:  "NODE_PAPER",
		6:  "NODE_BOOK",
		7:  "NODE_NOVELLA",
		8:  "NODE_GAME",
		9:  "NODE_ALBUM",
		10: "NODE_SONG",
		11: "NODE_PODCAST",
	}
	NodeType_value = map[string]int32{
		"NODE_UNKNOWN":  0,
		"NODE_SEMANTIC": 1,
		"NODE_TV":       2,
		"NODE_MOVIE":    3,
		"NODE_VIDEO":    4,
		"NODE_PAPER":    5,
		"NODE_BOOK":     6,
		"NODE_NOVELLA":  7,
		"NODE_GAME":     8,
		"NODE_ALBUM":    9,
		"NODE_SONG":     10,
		"NODE_PODCAST":  11,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_proto_data_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

type Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Query:
	//
	//	*Query_QueryNode
	//	*Query_QueryAtom
	Query         isQuery_Query `protobuf_oneof:"query"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *Query) GetQuery() isQuery_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *Query) GetQueryNode() string {
	if x != nil {
		if x, ok := x.Query.(*Query_QueryNode); ok {
			return x.QueryNode
		}
	}
	return ""
}

func (x *Query) GetQueryAtom() *QueryAtom {
	if x != nil {
		if x, ok := x.Query.(*Query_QueryAtom); ok {
			return x.QueryAtom
		}
	}
	return nil
}

type isQuery_Query interface {
	isQuery_Query()
}

type Query_QueryNode struct {
	QueryNode string `protobuf:"bytes,1,opt,name=query_node,json=queryNode,proto3,oneof"`
}

type Query_QueryAtom struct {
	QueryAtom *QueryAtom `protobuf:"bytes,2,opt,name=query_atom,json=queryAtom,proto3,oneof"`
}

func (*Query_QueryNode) isQuery_Query() {}

func (*Query_QueryAtom) isQuery_Query() {}

type QueryAtom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NodeType               `protobuf:"varint,2,opt,name=type,proto3,enum=bene.data.NodeType" json:"type,omitempty"`
	Atom          *Atom                  `protobuf:"bytes,3,opt,name=atom,proto3" json:"atom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAtom) Reset() {
	*x = QueryAtom{}
	mi := &file_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAtom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAtom) ProtoMessage() {}

func (x *QueryAtom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAtom.ProtoReflect.Descriptor instead.
func (*QueryAtom) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *QueryAtom) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_NODE_UNKNOWN
}

func (x *QueryAtom) GetAtom() *Atom {
	if x != nil {
		return x.Atom
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NodeType               `protobuf:"varint,1,opt,name=type,proto3,enum=bene.data.NodeType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	IsQueued      bool                   `protobuf:"varint,4,opt,name=is_queued,json=isQueued,proto3" json:"is_queued,omitempty"`
	Atoms         []*Atom                `protobuf:"bytes,5,rep,name=atoms,proto3" json:"atoms,omitempty"`
	Related       []*Node                `protobuf:"bytes,6,rep,name=related,proto3" json:"related,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_NODE_UNKNOWN
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Node) GetIsQueued() bool {
	if x != nil {
		return x.IsQueued
	}
	return false
}

func (x *Node) GetAtoms() []*Atom {
	if x != nil {
		return x.Atoms
	}
	return nil
}

func (x *Node) GetRelated() []*Node {
	if x != nil {
		return x.Related
	}
	return nil
}

type Title struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Localization  string                 `protobuf:"bytes,2,opt,name=localization,proto3" json:"localization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *Title) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Title) GetLocalization() string {
	if x != nil {
		return x.Localization
	}
	return ""
}

type Atom struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Api        api.API                `protobuf:"varint,1,opt,name=api,proto3,enum=bene.api.API" json:"api,omitempty"`
	Id         string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Titles     []*Title               `protobuf:"bytes,3,rep,name=titles,proto3" json:"titles,omitempty"`
	PreviewUrl string                 `protobuf:"bytes,4,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	Score      int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"` // Valid range [0, 100]
	IsDirty    bool                   `protobuf:"varint,6,opt,name=is_dirty,json=isDirty,proto3" json:"is_dirty,omitempty"`
	// Types that are valid to be assigned to Metadata:
	//
	//	*Atom_MetadataTv
	//	*Atom_MetadataMovie
	//	*Atom_MetadataVideo
	//	*Atom_MetadataPaper
	//	*Atom_MetadataBook
	//	*Atom_MetadataNovella
	//	*Atom_MetadataGame
	//	*Atom_MetadataAlbum
	//	*Atom_MetadataSong
	//	*Atom_MetadataPodcast
	Metadata      isAtom_Metadata `protobuf_oneof:"metadata"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Atom) Reset() {
	*x = Atom{}
	mi := &file_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Atom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Atom) ProtoMessage() {}

func (x *Atom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Atom.ProtoReflect.Descriptor instead.
func (*Atom) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{4}
}

func (x *Atom) GetApi() api.API {
	if x != nil {
		return x.Api
	}
	return api.API(0)
}

func (x *Atom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Atom) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *Atom) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *Atom) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Atom) GetIsDirty() bool {
	if x != nil {
		return x.IsDirty
	}
	return false
}

func (x *Atom) GetMetadata() isAtom_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Atom) GetMetadataTv() *MetadataTV {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataTv); ok {
			return x.MetadataTv
		}
	}
	return nil
}

func (x *Atom) GetMetadataMovie() *MetadataMovie {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataMovie); ok {
			return x.MetadataMovie
		}
	}
	return nil
}

func (x *Atom) GetMetadataVideo() *MetadataVideo {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataVideo); ok {
			return x.MetadataVideo
		}
	}
	return nil
}

func (x *Atom) GetMetadataPaper() *MetadataPaper {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataPaper); ok {
			return x.MetadataPaper
		}
	}
	return nil
}

func (x *Atom) GetMetadataBook() *MetadataBook {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataBook); ok {
			return x.MetadataBook
		}
	}
	return nil
}

func (x *Atom) GetMetadataNovella() *MetadataNovella {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataNovella); ok {
			return x.MetadataNovella
		}
	}
	return nil
}

func (x *Atom) GetMetadataGame() *MetadataGame {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataGame); ok {
			return x.MetadataGame
		}
	}
	return nil
}

func (x *Atom) GetMetadataAlbum() *MetadataAlbum {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataAlbum); ok {
			return x.MetadataAlbum
		}
	}
	return nil
}

func (x *Atom) GetMetadataSong() *MetadataSong {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataSong); ok {
			return x.MetadataSong
		}
	}
	return nil
}

func (x *Atom) GetMetadataPodcast() *MetadataPodcast {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataPodcast); ok {
			return x.MetadataPodcast
		}
	}
	return nil
}

type isAtom_Metadata interface {
	isAtom_Metadata()
}

type Atom_MetadataTv struct {
	MetadataTv *MetadataTV `protobuf:"bytes,100,opt,name=metadata_tv,json=metadataTv,proto3,oneof"`
}

type Atom_MetadataMovie struct {
	MetadataMovie *MetadataMovie `protobuf:"bytes,101,opt,name=metadata_movie,json=metadataMovie,proto3,oneof"`
}

type Atom_MetadataVideo struct {
	MetadataVideo *MetadataVideo `protobuf:"bytes,102,opt,name=metadata_video,json=metadataVideo,proto3,oneof"`
}

type Atom_MetadataPaper struct {
	MetadataPaper *MetadataPaper `protobuf:"bytes,103,opt,name=metadata_paper,json=metadataPaper,proto3,oneof"`
}

type Atom_MetadataBook struct {
	MetadataBook *MetadataBook `protobuf:"bytes,104,opt,name=metadata_book,json=metadataBook,proto3,oneof"`
}

type Atom_MetadataNovella struct {
	MetadataNovella *MetadataNovella `protobuf:"bytes,105,opt,name=metadata_novella,json=metadataNovella,proto3,oneof"`
}

type Atom_MetadataGame struct {
	MetadataGame *MetadataGame `protobuf:"bytes,106,opt,name=metadata_game,json=metadataGame,proto3,oneof"`
}

type Atom_MetadataAlbum struct {
	MetadataAlbum *MetadataAlbum `protobuf:"bytes,107,opt,name=metadata_album,json=metadataAlbum,proto3,oneof"`
}

type Atom_MetadataSong struct {
	MetadataSong *MetadataSong `protobuf:"bytes,108,opt,name=metadata_song,json=metadataSong,proto3,oneof"`
}

type Atom_MetadataPodcast struct {
	MetadataPodcast *MetadataPodcast `protobuf:"bytes,109,opt,name=metadata_podcast,json=metadataPodcast,proto3,oneof"`
}

func (*Atom_MetadataTv) isAtom_Metadata() {}

func (*Atom_MetadataMovie) isAtom_Metadata() {}

func (*Atom_MetadataVideo) isAtom_Metadata() {}

func (*Atom_MetadataPaper) isAtom_Metadata() {}

func (*Atom_MetadataBook) isAtom_Metadata() {}

func (*Atom_MetadataNovella) isAtom_Metadata() {}

func (*Atom_MetadataGame) isAtom_Metadata() {}

func (*Atom_MetadataAlbum) isAtom_Metadata() {}

func (*Atom_MetadataSong) isAtom_Metadata() {}

func (*Atom_MetadataPodcast) isAtom_Metadata() {}

type MetadataTV struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Season int32                  `protobuf:"varint,1,opt,name=season,proto3" json:"season,omitempty"` // Used if tracking a single
	// season, e.g. One Punch Man
	Genres        []string          `protobuf:"bytes,3,rep,name=genres,proto3" json:"genres,omitempty"`
	Showrunners   []string          `protobuf:"bytes,4,rep,name=showrunners,proto3" json:"showrunners,omitempty"`
	MetadataVideo *MetadataAuxVideo `protobuf:"bytes,5,opt,name=metadata_video,json=metadataVideo,proto3" json:"metadata_video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataTV) Reset() {
	*x = MetadataTV{}
	mi := &file_proto_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataTV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataTV) ProtoMessage() {}

func (x *MetadataTV) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataTV.ProtoReflect.Descriptor instead.
func (*MetadataTV) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{5}
}

func (x *MetadataTV) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *MetadataTV) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MetadataTV) GetShowrunners() []string {
	if x != nil {
		return x.Showrunners
	}
	return nil
}

func (x *MetadataTV) GetMetadataVideo() *MetadataAuxVideo {
	if x != nil {
		return x.MetadataVideo
	}
	return nil
}

type MetadataMovie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetadataVideo *MetadataAuxVideo      `protobuf:"bytes,1,opt,name=metadata_video,json=metadataVideo,proto3" json:"metadata_video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataMovie) Reset() {
	*x = MetadataMovie{}
	mi := &file_proto_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataMovie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataMovie) ProtoMessage() {}

func (x *MetadataMovie) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataMovie.ProtoReflect.Descriptor instead.
func (*MetadataMovie) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{6}
}

func (x *MetadataMovie) GetMetadataVideo() *MetadataAuxVideo {
	if x != nil {
		return x.MetadataVideo
	}
	return nil
}

type MetadataAuxVideo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsAnimated       bool                   `protobuf:"varint,1,opt,name=is_animated,json=isAnimated,proto3" json:"is_animated,omitempty"`
	Directors        []string               `protobuf:"bytes,2,rep,name=directors,proto3" json:"directors,omitempty"`
	Writers          []string               `protobuf:"bytes,3,rep,name=writers,proto3" json:"writers,omitempty"`
	Cinematography   []string               `protobuf:"bytes,4,rep,name=cinematography,proto3" json:"cinematography,omitempty"`
	Composers        []string               `protobuf:"bytes,5,rep,name=composers,proto3" json:"composers,omitempty"`
	Starring         []string               `protobuf:"bytes,6,rep,name=starring,proto3" json:"starring,omitempty"`
	AnimationStudios []string               `protobuf:"bytes,7,rep,name=animation_studios,json=animationStudios,proto3" json:"animation_studios,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetadataAuxVideo) Reset() {
	*x = MetadataAuxVideo{}
	mi := &file_proto_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataAuxVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataAuxVideo) ProtoMessage() {}

func (x *MetadataAuxVideo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataAuxVideo.ProtoReflect.Descriptor instead.
func (*MetadataAuxVideo) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{7}
}

func (x *MetadataAuxVideo) GetIsAnimated() bool {
	if x != nil {
		return x.IsAnimated
	}
	return false
}

func (x *MetadataAuxVideo) GetDirectors() []string {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *MetadataAuxVideo) GetWriters() []string {
	if x != nil {
		return x.Writers
	}
	return nil
}

func (x *MetadataAuxVideo) GetCinematography() []string {
	if x != nil {
		return x.Cinematography
	}
	return nil
}

func (x *MetadataAuxVideo) GetComposers() []string {
	if x != nil {
		return x.Composers
	}
	return nil
}

func (x *MetadataAuxVideo) GetStarring() []string {
	if x != nil {
		return x.Starring
	}
	return nil
}

func (x *MetadataAuxVideo) GetAnimationStudios() []string {
	if x != nil {
		return x.AnimationStudios
	}
	return nil
}

type MetadataVideo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       []string               `protobuf:"bytes,1,rep,name=creator,proto3" json:"creator,omitempty"` // e.g. EthosLab
	VideoUrl      string                 `protobuf:"bytes,2,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataVideo) Reset() {
	*x = MetadataVideo{}
	mi := &file_proto_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataVideo) ProtoMessage() {}

func (x *MetadataVideo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataVideo.ProtoReflect.Descriptor instead.
func (*MetadataVideo) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{8}
}

func (x *MetadataVideo) GetCreator() []string {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *MetadataVideo) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type MetadataPaper struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Authors         []string               `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	PublicationDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=publication_date,json=publicationDate,proto3" json:"publication_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetadataPaper) Reset() {
	*x = MetadataPaper{}
	mi := &file_proto_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataPaper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataPaper) ProtoMessage() {}

func (x *MetadataPaper) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataPaper.ProtoReflect.Descriptor instead.
func (*MetadataPaper) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{9}
}

func (x *MetadataPaper) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *MetadataPaper) GetPublicationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PublicationDate
	}
	return nil
}

type MetadataBook struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Series int32                  `protobuf:"varint,1,opt,name=series,proto3" json:"series,omitempty"` // Used if tracking
	// as part of a
	// series, e.g. The
	// Two Towers
	IsAnimated         bool                   `protobuf:"varint,2,opt,name=is_animated,json=isAnimated,proto3" json:"is_animated,omitempty"`
	Genres             []string               `protobuf:"bytes,3,rep,name=genres,proto3" json:"genres,omitempty"`
	MetadataLiterature *MetadataAuxLiterature `protobuf:"bytes,4,opt,name=metadata_literature,json=metadataLiterature,proto3" json:"metadata_literature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetadataBook) Reset() {
	*x = MetadataBook{}
	mi := &file_proto_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataBook) ProtoMessage() {}

func (x *MetadataBook) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataBook.ProtoReflect.Descriptor instead.
func (*MetadataBook) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{10}
}

func (x *MetadataBook) GetSeries() int32 {
	if x != nil {
		return x.Series
	}
	return 0
}

func (x *MetadataBook) GetIsAnimated() bool {
	if x != nil {
		return x.IsAnimated
	}
	return false
}

func (x *MetadataBook) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MetadataBook) GetMetadataLiterature() *MetadataAuxLiterature {
	if x != nil {
		return x.MetadataLiterature
	}
	return nil
}

type MetadataNovella struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MetadataLiterature *MetadataAuxLiterature `protobuf:"bytes,1,opt,name=metadata_literature,json=metadataLiterature,proto3" json:"metadata_literature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetadataNovella) Reset() {
	*x = MetadataNovella{}
	mi := &file_proto_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataNovella) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataNovella) ProtoMessage() {}

func (x *MetadataNovella) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataNovella.ProtoReflect.Descriptor instead.
func (*MetadataNovella) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{11}
}

func (x *MetadataNovella) GetMetadataLiterature() *MetadataAuxLiterature {
	if x != nil {
		return x.MetadataLiterature
	}
	return nil
}

type MetadataAuxLiterature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []string               `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	Illustrators  []string               `protobuf:"bytes,2,rep,name=illustrators,proto3" json:"illustrators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataAuxLiterature) Reset() {
	*x = MetadataAuxLiterature{}
	mi := &file_proto_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataAuxLiterature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataAuxLiterature) ProtoMessage() {}

func (x *MetadataAuxLiterature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataAuxLiterature.ProtoReflect.Descriptor instead.
func (*MetadataAuxLiterature) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{12}
}

func (x *MetadataAuxLiterature) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *MetadataAuxLiterature) GetIllustrators() []string {
	if x != nil {
		return x.Illustrators
	}
	return nil
}

type MetadataGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Developers    []string               `protobuf:"bytes,1,rep,name=developers,proto3" json:"developers,omitempty"`
	Directors     []string               `protobuf:"bytes,2,rep,name=directors,proto3" json:"directors,omitempty"`
	Artists       []string               `protobuf:"bytes,3,rep,name=artists,proto3" json:"artists,omitempty"`
	Composers     []string               `protobuf:"bytes,4,rep,name=composers,proto3" json:"composers,omitempty"`
	Genres        []string               `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataGame) Reset() {
	*x = MetadataGame{}
	mi := &file_proto_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataGame) ProtoMessage() {}

func (x *MetadataGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataGame.ProtoReflect.Descriptor instead.
func (*MetadataGame) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{13}
}

func (x *MetadataGame) GetDevelopers() []string {
	if x != nil {
		return x.Developers
	}
	return nil
}

func (x *MetadataGame) GetDirectors() []string {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *MetadataGame) GetArtists() []string {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *MetadataGame) GetComposers() []string {
	if x != nil {
		return x.Composers
	}
	return nil
}

func (x *MetadataGame) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type MetadataAlbum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []string               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	MetadataAudio *MetadataAuxAudio      `protobuf:"bytes,2,opt,name=metadata_audio,json=metadataAudio,proto3" json:"metadata_audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataAlbum) Reset() {
	*x = MetadataAlbum{}
	mi := &file_proto_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataAlbum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataAlbum) ProtoMessage() {}

func (x *MetadataAlbum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataAlbum.ProtoReflect.Descriptor instead.
func (*MetadataAlbum) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{14}
}

func (x *MetadataAlbum) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MetadataAlbum) GetMetadataAudio() *MetadataAuxAudio {
	if x != nil {
		return x.MetadataAudio
	}
	return nil
}

type MetadataSong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         int32                  `protobuf:"varint,1,opt,name=track,proto3" json:"track,omitempty"`
	MetadataAudio *MetadataAuxAudio      `protobuf:"bytes,2,opt,name=metadata_audio,json=metadataAudio,proto3" json:"metadata_audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataSong) Reset() {
	*x = MetadataSong{}
	mi := &file_proto_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataSong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataSong) ProtoMessage() {}

func (x *MetadataSong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataSong.ProtoReflect.Descriptor instead.
func (*MetadataSong) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{15}
}

func (x *MetadataSong) GetTrack() int32 {
	if x != nil {
		return x.Track
	}
	return 0
}

func (x *MetadataSong) GetMetadataAudio() *MetadataAuxAudio {
	if x != nil {
		return x.MetadataAudio
	}
	return nil
}

type MetadataAuxAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artists       []string               `protobuf:"bytes,1,rep,name=artists,proto3" json:"artists,omitempty"`
	Writers       []string               `protobuf:"bytes,2,rep,name=writers,proto3" json:"writers,omitempty"`
	Composers     []string               `protobuf:"bytes,3,rep,name=composers,proto3" json:"composers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataAuxAudio) Reset() {
	*x = MetadataAuxAudio{}
	mi := &file_proto_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataAuxAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataAuxAudio) ProtoMessage() {}

func (x *MetadataAuxAudio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataAuxAudio.ProtoReflect.Descriptor instead.
func (*MetadataAuxAudio) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{16}
}

func (x *MetadataAuxAudio) GetArtists() []string {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *MetadataAuxAudio) GetWriters() []string {
	if x != nil {
		return x.Writers
	}
	return nil
}

func (x *MetadataAuxAudio) GetComposers() []string {
	if x != nil {
		return x.Composers
	}
	return nil
}

type MetadataPodcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []string               `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Genres        []string               `protobuf:"bytes,2,rep,name=genres,proto3" json:"genres,omitempty"`
	Narrators     []string               `protobuf:"bytes,3,rep,name=narrators,proto3" json:"narrators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataPodcast) Reset() {
	*x = MetadataPodcast{}
	mi := &file_proto_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataPodcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataPodcast) ProtoMessage() {}

func (x *MetadataPodcast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataPodcast.ProtoReflect.Descriptor instead.
func (*MetadataPodcast) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{17}
}

func (x *MetadataPodcast) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *MetadataPodcast) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MetadataPodcast) GetNarrators() []string {
	if x != nil {
		return x.Narrators
	}
	return nil
}

var File_proto_data_proto protoreflect.FileDescriptor

const file_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x10proto/data.proto\x12\tbene.data\x1a\x0fproto/api.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"h\n" +
	"\x05Query\x12\x1f\n" +
	"\n" +
	"query_node\x18\x01 \x01(\tH\x00R\tqueryNode\x125\n" +
	"\n" +
	"query_atom\x18\x02 \x01(\v2\x14.bene.data.QueryAtomH\x00R\tqueryAtomB\a\n" +
	"\x05query\"Y\n" +
	"\tQueryAtom\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.bene.data.NodeTypeR\x04type\x12#\n" +
	"\x04atom\x18\x03 \x01(\v2\x0f.bene.data.AtomR\x04atom\"\xc6\x01\n" +
	"\x04Node\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.bene.data.NodeTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x1b\n" +
	"\tis_queued\x18\x04 \x01(\bR\bisQueued\x12%\n" +
	"\x05atoms\x18\x05 \x03(\v2\x0f.bene.data.AtomR\x05atoms\x12)\n" +
	"\arelated\x18\x06 \x03(\v2\x0f.bene.data.NodeR\arelated\"A\n" +
	"\x05Title\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\"\n" +
	"\flocalization\x18\x02 \x01(\tR\flocalization\"\xd7\x06\n" +
	"\x04Atom\x12\x1f\n" +
	"\x03api\x18\x01 \x01(\x0e2\r.bene.api.APIR\x03api\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12(\n" +
	"\x06titles\x18\x03 \x03(\v2\x10.bene.data.TitleR\x06titles\x12\x1f\n" +
	"\vpreview_url\x18\x04 \x01(\tR\n" +
	"previewUrl\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12\x19\n" +
	"\bis_dirty\x18\x06 \x01(\bR\aisDirty\x128\n" +
	"\vmetadata_tv\x18d \x01(\v2\x15.bene.data.MetadataTVH\x00R\n" +
	"metadataTv\x12A\n" +
	"\x0emetadata_movie\x18e \x01(\v2\x18.bene.data.MetadataMovieH\x00R\rmetadataMovie\x12A\n" +
	"\x0emetadata_video\x18f \x01(\v2\x18.bene.data.MetadataVideoH\x00R\rmetadataVideo\x12A\n" +
	"\x0emetadata_paper\x18g \x01(\v2\x18.bene.data.MetadataPaperH\x00R\rmetadataPaper\x12>\n" +
	"\rmetadata_book\x18h \x01(\v2\x17.bene.data.MetadataBookH\x00R\fmetadataBook\x12G\n" +
	"\x10metadata_novella\x18i \x01(\v2\x1a.bene.data.MetadataNovellaH\x00R\x0fmetadataNovella\x12>\n" +
	"\rmetadata_game\x18j \x01(\v2\x17.bene.data.MetadataGameH\x00R\fmetadataGame\x12A\n" +
	"\x0emetadata_album\x18k \x01(\v2\x18.bene.data.MetadataAlbumH\x00R\rmetadataAlbum\x12>\n" +
	"\rmetadata_song\x18l \x01(\v2\x17.bene.data.MetadataSongH\x00R\fmetadataSong\x12G\n" +
	"\x10metadata_podcast\x18m \x01(\v2\x1a.bene.data.MetadataPodcastH\x00R\x0fmetadataPodcastB\n" +
	"\n" +
	"\bmetadata\"\xa2\x01\n" +
	"\n" +
	"MetadataTV\x12\x16\n" +
	"\x06season\x18\x01 \x01(\x05R\x06season\x12\x16\n" +
	"\x06genres\x18\x03 \x03(\tR\x06genres\x12 \n" +
	"\vshowrunners\x18\x04 \x03(\tR\vshowrunners\x12B\n" +
	"\x0emetadata_video\x18\x05 \x01(\v2\x1b.bene.data.MetadataAuxVideoR\rmetadataVideo\"S\n" +
	"\rMetadataMovie\x12B\n" +
	"\x0emetadata_video\x18\x01 \x01(\v2\x1b.bene.data.MetadataAuxVideoR\rmetadataVideo\"\xfa\x01\n" +
	"\x10MetadataAuxVideo\x12\x1f\n" +
	"\vis_animated\x18\x01 \x01(\bR\n" +
	"isAnimated\x12\x1c\n" +
	"\tdirectors\x18\x02 \x03(\tR\tdirectors\x12\x18\n" +
	"\awriters\x18\x03 \x03(\tR\awriters\x12&\n" +
	"\x0ecinematography\x18\x04 \x03(\tR\x0ecinematography\x12\x1c\n" +
	"\tcomposers\x18\x05 \x03(\tR\tcomposers\x12\x1a\n" +
	"\bstarring\x18\x06 \x03(\tR\bstarring\x12+\n" +
	"\x11animation_studios\x18\a \x03(\tR\x10animationStudios\"F\n" +
	"\rMetadataVideo\x12\x18\n" +
	"\acreator\x18\x01 \x03(\tR\acreator\x12\x1b\n" +
	"\tvideo_url\x18\x02 \x01(\tR\bvideoUrl\"p\n" +
	"\rMetadataPaper\x12\x18\n" +
	"\aauthors\x18\x01 \x03(\tR\aauthors\x12E\n" +
	"\x10publication_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0fpublicationDate\"\xb2\x01\n" +
	"\fMetadataBook\x12\x16\n" +
	"\x06series\x18\x01 \x01(\x05R\x06series\x12\x1f\n" +
	"\vis_animated\x18\x02 \x01(\bR\n" +
	"isAnimated\x12\x16\n" +
	"\x06genres\x18\x03 \x03(\tR\x06genres\x12Q\n" +
	"\x13metadata_literature\x18\x04 \x01(\v2 .bene.data.MetadataAuxLiteratureR\x12metadataLiterature\"d\n" +
	"\x0fMetadataNovella\x12Q\n" +
	"\x13metadata_literature\x18\x01 \x01(\v2 .bene.data.MetadataAuxLiteratureR\x12metadataLiterature\"U\n" +
	"\x15MetadataAuxLiterature\x12\x18\n" +
	"\aauthors\x18\x01 \x03(\tR\aauthors\x12\"\n" +
	"\fillustrators\x18\x02 \x03(\tR\fillustrators\"\x9c\x01\n" +
	"\fMetadataGame\x12\x1e\n" +
	"\n" +
	"developers\x18\x01 \x03(\tR\n" +
	"developers\x12\x1c\n" +
	"\tdirectors\x18\x02 \x03(\tR\tdirectors\x12\x18\n" +
	"\aartists\x18\x03 \x03(\tR\aartists\x12\x1c\n" +
	"\tcomposers\x18\x04 \x03(\tR\tcomposers\x12\x16\n" +
	"\x06genres\x18\x05 \x03(\tR\x06genres\"k\n" +
	"\rMetadataAlbum\x12\x16\n" +
	"\x06genres\x18\x01 \x03(\tR\x06genres\x12B\n" +
	"\x0emetadata_audio\x18\x02 \x01(\v2\x1b.bene.data.MetadataAuxAudioR\rmetadataAudio\"h\n" +
	"\fMetadataSong\x12\x14\n" +
	"\x05track\x18\x01 \x01(\x05R\x05track\x12B\n" +
	"\x0emetadata_audio\x18\x02 \x01(\v2\x1b.bene.data.MetadataAuxAudioR\rmetadataAudio\"d\n" +
	"\x10MetadataAuxAudio\x12\x18\n" +
	"\aartists\x18\x01 \x03(\tR\aartists\x12\x18\n" +
	"\awriters\x18\x02 \x03(\tR\awriters\x12\x1c\n" +
	"\tcomposers\x18\x03 \x03(\tR\tcomposers\"]\n" +
	"\x0fMetadataPodcast\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12\x16\n" +
	"\x06genres\x18\x02 \x03(\tR\x06genres\x12\x1c\n" +
	"\tnarrators\x18\x03 \x03(\tR\tnarrators*\xcd\x01\n" +
	"\bNodeType\x12\x10\n" +
	"\fNODE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rNODE_SEMANTIC\x10\x01\x12\v\n" +
	"\aNODE_TV\x10\x02\x12\x0e\n" +
	"\n" +
	"NODE_MOVIE\x10\x03\x12\x0e\n" +
	"\n" +
	"NODE_VIDEO\x10\x04\x12\x0e\n" +
	"\n" +
	"NODE_PAPER\x10\x05\x12\r\n" +
	"\tNODE_BOOK\x10\x06\x12\x10\n" +
	"\fNODE_NOVELLA\x10\a\x12\r\n" +
	"\tNODE_GAME\x10\b\x12\x0e\n" +
	"\n" +
	"NODE_ALBUM\x10\t\x12\r\n" +
	"\tNODE_SONG\x10\n" +
	"\x12\x10\n" +
	"\fNODE_PODCAST\x10\vB.Z,github.com/minkezhang/bene-api/proto/go/datab\x06proto3"

var (
	file_proto_data_proto_rawDescOnce sync.Once
	file_proto_data_proto_rawDescData []byte
)

func file_proto_data_proto_rawDescGZIP() []byte {
	file_proto_data_proto_rawDescOnce.Do(func() {
		file_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)))
	})
	return file_proto_data_proto_rawDescData
}

var file_proto_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_data_proto_goTypes = []any{
	(NodeType)(0),                 // 0: bene.data.NodeType
	(*Query)(nil),                 // 1: bene.data.Query
	(*QueryAtom)(nil),             // 2: bene.data.QueryAtom
	(*Node)(nil),                  // 3: bene.data.Node
	(*Title)(nil),                 // 4: bene.data.Title
	(*Atom)(nil),                  // 5: bene.data.Atom
	(*MetadataTV)(nil),            // 6: bene.data.MetadataTV
	(*MetadataMovie)(nil),         // 7: bene.data.MetadataMovie
	(*MetadataAuxVideo)(nil),      // 8: bene.data.MetadataAuxVideo
	(*MetadataVideo)(nil),         // 9: bene.data.MetadataVideo
	(*MetadataPaper)(nil),         // 10: bene.data.MetadataPaper
	(*MetadataBook)(nil),          // 11: bene.data.MetadataBook
	(*MetadataNovella)(nil),       // 12: bene.data.MetadataNovella
	(*MetadataAuxLiterature)(nil), // 13: bene.data.MetadataAuxLiterature
	(*MetadataGame)(nil),          // 14: bene.data.MetadataGame
	(*MetadataAlbum)(nil),         // 15: bene.data.MetadataAlbum
	(*MetadataSong)(nil),          // 16: bene.data.MetadataSong
	(*MetadataAuxAudio)(nil),      // 17: bene.data.MetadataAuxAudio
	(*MetadataPodcast)(nil),       // 18: bene.data.MetadataPodcast
	(api.API)(0),                  // 19: bene.api.API
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_proto_data_proto_depIdxs = []int32{
	2,  // 0: bene.data.Query.query_atom:type_name -> bene.data.QueryAtom
	0,  // 1: bene.data.QueryAtom.type:type_name -> bene.data.NodeType
	5,  // 2: bene.data.QueryAtom.atom:type_name -> bene.data.Atom
	0,  // 3: bene.data.Node.type:type_name -> bene.data.NodeType
	5,  // 4: bene.data.Node.atoms:type_name -> bene.data.Atom
	3,  // 5: bene.data.Node.related:type_name -> bene.data.Node
	19, // 6: bene.data.Atom.api:type_name -> bene.api.API
	4,  // 7: bene.data.Atom.titles:type_name -> bene.data.Title
	6,  // 8: bene.data.Atom.metadata_tv:type_name -> bene.data.MetadataTV
	7,  // 9: bene.data.Atom.metadata_movie:type_name -> bene.data.MetadataMovie
	9,  // 10: bene.data.Atom.metadata_video:type_name -> bene.data.MetadataVideo
	10, // 11: bene.data.Atom.metadata_paper:type_name -> bene.data.MetadataPaper
	11, // 12: bene.data.Atom.metadata_book:type_name -> bene.data.MetadataBook
	12, // 13: bene.data.Atom.metadata_novella:type_name -> bene.data.MetadataNovella
	14, // 14: bene.data.Atom.metadata_game:type_name -> bene.data.MetadataGame
	15, // 15: bene.data.Atom.metadata_album:type_name -> bene.data.MetadataAlbum
	16, // 16: bene.data.Atom.metadata_song:type_name -> bene.data.MetadataSong
	18, // 17: bene.data.Atom.metadata_podcast:type_name -> bene.data.MetadataPodcast
	8,  // 18: bene.data.MetadataTV.metadata_video:type_name -> bene.data.MetadataAuxVideo
	8,  // 19: bene.data.MetadataMovie.metadata_video:type_name -> bene.data.MetadataAuxVideo
	20, // 20: bene.data.MetadataPaper.publication_date:type_name -> google.protobuf.Timestamp
	13, // 21: bene.data.MetadataBook.metadata_literature:type_name -> bene.data.MetadataAuxLiterature
	13, // 22: bene.data.MetadataNovella.metadata_literature:type_name -> bene.data.MetadataAuxLiterature
	17, // 23: bene.data.MetadataAlbum.metadata_audio:type_name -> bene.data.MetadataAuxAudio
	17, // 24: bene.data.MetadataSong.metadata_audio:type_name -> bene.data.MetadataAuxAudio
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_data_proto_init() }
func file_proto_data_proto_init() {
	if File_proto_data_proto != nil {
		return
	}
	file_proto_data_proto_msgTypes[0].OneofWrappers = []any{
		(*Query_QueryNode)(nil),
		(*Query_QueryAtom)(nil),
	}
	file_proto_data_proto_msgTypes[4].OneofWrappers = []any{
		(*Atom_MetadataTv)(nil),
		(*Atom_MetadataMovie)(nil),
		(*Atom_MetadataVideo)(nil),
		(*Atom_MetadataPaper)(nil),
		(*Atom_MetadataBook)(nil),
		(*Atom_MetadataNovella)(nil),
		(*Atom_MetadataGame)(nil),
		(*Atom_MetadataAlbum)(nil),
		(*Atom_MetadataSong)(nil),
		(*Atom_MetadataPodcast)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_data_proto_goTypes,
		DependencyIndexes: file_proto_data_proto_depIdxs,
		EnumInfos:         file_proto_data_proto_enumTypes,
		MessageInfos:      file_proto_data_proto_msgTypes,
	}.Build()
	File_proto_data_proto = out.File
	file_proto_data_proto_goTypes = nil
	file_proto_data_proto_depIdxs = nil
}
