// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/data.proto

package data

import (
	enums "github.com/minkezhang/truffle-api/proto/go/enums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Sources       []*Source              `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *Database) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Database) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

type Title struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Localization  string                 `protobuf:"bytes,2,opt,name=localization,proto3" json:"localization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *Title) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Title) GetLocalization() string {
	if x != nil {
		return x.Localization
	}
	return ""
}

// Node is comprised of multiple source instances.
//
// All sources within the same node must have the same source type and
// source tag.
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *NodeHeader            `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetHeader() *NodeHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type NodeHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          enums.SourceType       `protobuf:"varint,1,opt,name=type,proto3,enum=truffle.enums.SourceType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHeader) Reset() {
	*x = NodeHeader{}
	mi := &file_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeader) ProtoMessage() {}

func (x *NodeHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeader.ProtoReflect.Descriptor instead.
func (*NodeHeader) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *NodeHeader) GetType() enums.SourceType {
	if x != nil {
		return x.Type
	}
	return enums.SourceType(0)
}

func (x *NodeHeader) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SourceHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Api           enums.SourceAPI        `protobuf:"varint,1,opt,name=api,proto3,enum=truffle.enums.SourceAPI" json:"api,omitempty"`
	Type          enums.SourceType       `protobuf:"varint,2,opt,name=type,proto3,enum=truffle.enums.SourceType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceHeader) Reset() {
	*x = SourceHeader{}
	mi := &file_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceHeader) ProtoMessage() {}

func (x *SourceHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceHeader.ProtoReflect.Descriptor instead.
func (*SourceHeader) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{4}
}

func (x *SourceHeader) GetApi() enums.SourceAPI {
	if x != nil {
		return x.Api
	}
	return enums.SourceAPI(0)
}

func (x *SourceHeader) GetType() enums.SourceType {
	if x != nil {
		return x.Type
	}
	return enums.SourceType(0)
}

func (x *SourceHeader) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Source struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Parent reference
	Header *SourceHeader          `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	// Data sources may link to other
	RelatedHeaders []*SourceHeader `protobuf:"bytes,3,rep,name=related_headers,json=relatedHeaders,proto3" json:"related_headers,omitempty"`
	// Common fields
	Titles     []*Title           `protobuf:"bytes,100,rep,name=titles,proto3" json:"titles,omitempty"`
	PreviewUrl string             `protobuf:"bytes,101,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	Score      int64              `protobuf:"varint,102,opt,name=score,proto3" json:"score,omitempty"` // 0 - 100
	Synopsis   string             `protobuf:"bytes,103,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	Notes      string             `protobuf:"bytes,104,opt,name=notes,proto3" json:"notes,omitempty"`
	Genres     []string           `protobuf:"bytes,105,rep,name=genres,proto3" json:"genres,omitempty"`
	Status     enums.SourceStatus `protobuf:"varint,106,opt,name=status,proto3,enum=truffle.enums.SourceStatus" json:"status,omitempty"`
	// Series and movie-specific fields
	Studios []string `protobuf:"bytes,200,rep,name=studios,proto3" json:"studios,omitempty"` // e.g. WIT, Gainax (anime-specific)
	Seasons []string `protobuf:"bytes,201,rep,name=seasons,proto3" json:"seasons,omitempty"` // e.g. 2010 Fall (anime-specific)
	// Book-specific fields
	Authors       []string               `protobuf:"bytes,300,rep,name=authors,proto3" json:"authors,omitempty"`
	Illustrators  []string               `protobuf:"bytes,301,rep,name=illustrators,proto3" json:"illustrators,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,302,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"` // Last time a chapter was released (manga-specific)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_proto_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{5}
}

func (x *Source) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Source) GetHeader() *SourceHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Source) GetRelatedHeaders() []*SourceHeader {
	if x != nil {
		return x.RelatedHeaders
	}
	return nil
}

func (x *Source) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *Source) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *Source) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Source) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *Source) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Source) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Source) GetStatus() enums.SourceStatus {
	if x != nil {
		return x.Status
	}
	return enums.SourceStatus(0)
}

func (x *Source) GetStudios() []string {
	if x != nil {
		return x.Studios
	}
	return nil
}

func (x *Source) GetSeasons() []string {
	if x != nil {
		return x.Seasons
	}
	return nil
}

func (x *Source) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Source) GetIllustrators() []string {
	if x != nil {
		return x.Illustrators
	}
	return nil
}

func (x *Source) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_proto_data_proto protoreflect.FileDescriptor

const file_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x10proto/data.proto\x12\ftruffle.data\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11proto/enums.proto\"d\n" +
	"\bDatabase\x12(\n" +
	"\x05nodes\x18\x01 \x03(\v2\x12.truffle.data.NodeR\x05nodes\x12.\n" +
	"\asources\x18\x02 \x03(\v2\x14.truffle.data.SourceR\asources\"A\n" +
	"\x05Title\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\"\n" +
	"\flocalization\x18\x02 \x01(\tR\flocalization\"8\n" +
	"\x04Node\x120\n" +
	"\x06header\x18\x01 \x01(\v2\x18.truffle.data.NodeHeaderR\x06header\"K\n" +
	"\n" +
	"NodeHeader\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.truffle.enums.SourceTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"y\n" +
	"\fSourceHeader\x12*\n" +
	"\x03api\x18\x01 \x01(\x0e2\x18.truffle.enums.SourceAPIR\x03api\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.truffle.enums.SourceTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xb3\x04\n" +
	"\x06Source\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x122\n" +
	"\x06header\x18\x02 \x01(\v2\x1a.truffle.data.SourceHeaderR\x06header\x12C\n" +
	"\x0frelated_headers\x18\x03 \x03(\v2\x1a.truffle.data.SourceHeaderR\x0erelatedHeaders\x12+\n" +
	"\x06titles\x18d \x03(\v2\x13.truffle.data.TitleR\x06titles\x12\x1f\n" +
	"\vpreview_url\x18e \x01(\tR\n" +
	"previewUrl\x12\x14\n" +
	"\x05score\x18f \x01(\x03R\x05score\x12\x1a\n" +
	"\bsynopsis\x18g \x01(\tR\bsynopsis\x12\x14\n" +
	"\x05notes\x18h \x01(\tR\x05notes\x12\x16\n" +
	"\x06genres\x18i \x03(\tR\x06genres\x123\n" +
	"\x06status\x18j \x01(\x0e2\x1b.truffle.enums.SourceStatusR\x06status\x12\x19\n" +
	"\astudios\x18\xc8\x01 \x03(\tR\astudios\x12\x19\n" +
	"\aseasons\x18\xc9\x01 \x03(\tR\aseasons\x12\x19\n" +
	"\aauthors\x18\xac\x02 \x03(\tR\aauthors\x12#\n" +
	"\fillustrators\x18\xad\x02 \x03(\tR\fillustrators\x12>\n" +
	"\flast_updated\x18\xae\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdatedB1Z/github.com/minkezhang/truffle-api/proto/go/datab\x06proto3"

var (
	file_proto_data_proto_rawDescOnce sync.Once
	file_proto_data_proto_rawDescData []byte
)

func file_proto_data_proto_rawDescGZIP() []byte {
	file_proto_data_proto_rawDescOnce.Do(func() {
		file_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)))
	})
	return file_proto_data_proto_rawDescData
}

var file_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_data_proto_goTypes = []any{
	(*Database)(nil),              // 0: truffle.data.Database
	(*Title)(nil),                 // 1: truffle.data.Title
	(*Node)(nil),                  // 2: truffle.data.Node
	(*NodeHeader)(nil),            // 3: truffle.data.NodeHeader
	(*SourceHeader)(nil),          // 4: truffle.data.SourceHeader
	(*Source)(nil),                // 5: truffle.data.Source
	(enums.SourceType)(0),         // 6: truffle.enums.SourceType
	(enums.SourceAPI)(0),          // 7: truffle.enums.SourceAPI
	(enums.SourceStatus)(0),       // 8: truffle.enums.SourceStatus
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_data_proto_depIdxs = []int32{
	2,  // 0: truffle.data.Database.nodes:type_name -> truffle.data.Node
	5,  // 1: truffle.data.Database.sources:type_name -> truffle.data.Source
	3,  // 2: truffle.data.Node.header:type_name -> truffle.data.NodeHeader
	6,  // 3: truffle.data.NodeHeader.type:type_name -> truffle.enums.SourceType
	7,  // 4: truffle.data.SourceHeader.api:type_name -> truffle.enums.SourceAPI
	6,  // 5: truffle.data.SourceHeader.type:type_name -> truffle.enums.SourceType
	4,  // 6: truffle.data.Source.header:type_name -> truffle.data.SourceHeader
	4,  // 7: truffle.data.Source.related_headers:type_name -> truffle.data.SourceHeader
	1,  // 8: truffle.data.Source.titles:type_name -> truffle.data.Title
	8,  // 9: truffle.data.Source.status:type_name -> truffle.enums.SourceStatus
	9,  // 10: truffle.data.Source.last_updated:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_data_proto_init() }
func file_proto_data_proto_init() {
	if File_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_data_proto_goTypes,
		DependencyIndexes: file_proto_data_proto_depIdxs,
		MessageInfos:      file_proto_data_proto_msgTypes,
	}.Build()
	File_proto_data_proto = out.File
	file_proto_data_proto_goTypes = nil
	file_proto_data_proto_depIdxs = nil
}
