// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/enums.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TYPE_NONE Type = 0
	Type_TYPE_TV   Type = 1
	Type_TYPE_BOOK Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_NONE",
		1: "TYPE_TV",
		2: "TYPE_BOOK",
	}
	Type_value = map[string]int32{
		"TYPE_NONE": 0,
		"TYPE_TV":   1,
		"TYPE_BOOK": 2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enums_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_proto_enums_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_enums_proto_rawDescGZIP(), []int{0}
}

type API int32

const (
	API_API_VIRTUAL API = 0
	API_API_BENE    API = 2
	// API_TRUFFLE      = 3;
	API_API_MAL API = 4
)

// Enum value maps for API.
var (
	API_name = map[int32]string{
		0: "API_VIRTUAL",
		2: "API_BENE",
		4: "API_MAL",
	}
	API_value = map[string]int32{
		"API_VIRTUAL": 0,
		"API_BENE":    2,
		"API_MAL":     4,
	}
)

func (x API) Enum() *API {
	p := new(API)
	*p = x
	return p
}

func (x API) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (API) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enums_proto_enumTypes[1].Descriptor()
}

func (API) Type() protoreflect.EnumType {
	return &file_proto_enums_proto_enumTypes[1]
}

func (x API) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use API.Descriptor instead.
func (API) EnumDescriptor() ([]byte, []int) {
	return file_proto_enums_proto_rawDescGZIP(), []int{1}
}

var File_proto_enums_proto protoreflect.FileDescriptor

const file_proto_enums_proto_rawDesc = "" +
	"\n" +
	"\x11proto/enums.proto\x12\n" +
	"bene.enums*1\n" +
	"\x04Type\x12\r\n" +
	"\tTYPE_NONE\x10\x00\x12\v\n" +
	"\aTYPE_TV\x10\x01\x12\r\n" +
	"\tTYPE_BOOK\x10\x02*1\n" +
	"\x03API\x12\x0f\n" +
	"\vAPI_VIRTUAL\x10\x00\x12\f\n" +
	"\bAPI_BENE\x10\x02\x12\v\n" +
	"\aAPI_MAL\x10\x04B/Z-github.com/minkezhang/bene-api/proto/go/enumsb\x06proto3"

var (
	file_proto_enums_proto_rawDescOnce sync.Once
	file_proto_enums_proto_rawDescData []byte
)

func file_proto_enums_proto_rawDescGZIP() []byte {
	file_proto_enums_proto_rawDescOnce.Do(func() {
		file_proto_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_enums_proto_rawDesc), len(file_proto_enums_proto_rawDesc)))
	})
	return file_proto_enums_proto_rawDescData
}

var file_proto_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_enums_proto_goTypes = []any{
	(Type)(0), // 0: bene.enums.Type
	(API)(0),  // 1: bene.enums.API
}
var file_proto_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enums_proto_init() }
func file_proto_enums_proto_init() {
	if File_proto_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_enums_proto_rawDesc), len(file_proto_enums_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enums_proto_goTypes,
		DependencyIndexes: file_proto_enums_proto_depIdxs,
		EnumInfos:         file_proto_enums_proto_enumTypes,
	}.Build()
	File_proto_enums_proto = out.File
	file_proto_enums_proto_goTypes = nil
	file_proto_enums_proto_depIdxs = nil
}
