// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: proto/enums.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TYPE_NONE Type = 0
	Type_TYPE_TV   Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_NONE",
		1: "TYPE_TV",
	}
	Type_value = map[string]int32{
		"TYPE_NONE": 0,
		"TYPE_TV":   1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enums_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_proto_enums_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_enums_proto_rawDescGZIP(), []int{0}
}

type API int32

const (
	API_API_VIRTUAL API = 0
	API_API_BENE    API = 2
	// API_TRUFFLE      = 3;
	API_API_MAL API = 4
)

// Enum value maps for API.
var (
	API_name = map[int32]string{
		0: "API_VIRTUAL",
		2: "API_BENE",
		4: "API_MAL",
	}
	API_value = map[string]int32{
		"API_VIRTUAL": 0,
		"API_BENE":    2,
		"API_MAL":     4,
	}
)

func (x API) Enum() *API {
	p := new(API)
	*p = x
	return p
}

func (x API) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (API) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enums_proto_enumTypes[1].Descriptor()
}

func (API) Type() protoreflect.EnumType {
	return &file_proto_enums_proto_enumTypes[1]
}

func (x API) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use API.Descriptor instead.
func (API) EnumDescriptor() ([]byte, []int) {
	return file_proto_enums_proto_rawDescGZIP(), []int{1}
}

var File_proto_enums_proto protoreflect.FileDescriptor

var file_proto_enums_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x62, 0x65, 0x6e, 0x65, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2a,
	0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54,
	0x56, 0x10, 0x01, 0x2a, 0x31, 0x0a, 0x03, 0x41, 0x50, 0x49, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x50,
	0x49, 0x5f, 0x56, 0x49, 0x52, 0x54, 0x55, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41,
	0x50, 0x49, 0x5f, 0x42, 0x45, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x50, 0x49,
	0x5f, 0x4d, 0x41, 0x4c, 0x10, 0x04, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6e, 0x6b, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2f,
	0x62, 0x65, 0x6e, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_enums_proto_rawDescOnce sync.Once
	file_proto_enums_proto_rawDescData = file_proto_enums_proto_rawDesc
)

func file_proto_enums_proto_rawDescGZIP() []byte {
	file_proto_enums_proto_rawDescOnce.Do(func() {
		file_proto_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_enums_proto_rawDescData)
	})
	return file_proto_enums_proto_rawDescData
}

var file_proto_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_enums_proto_goTypes = []interface{}{
	(Type)(0), // 0: bene.enums.Type
	(API)(0),  // 1: bene.enums.API
}
var file_proto_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enums_proto_init() }
func file_proto_enums_proto_init() {
	if File_proto_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_enums_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enums_proto_goTypes,
		DependencyIndexes: file_proto_enums_proto_depIdxs,
		EnumInfos:         file_proto_enums_proto_enumTypes,
	}.Build()
	File_proto_enums_proto = out.File
	file_proto_enums_proto_rawDesc = nil
	file_proto_enums_proto_goTypes = nil
	file_proto_enums_proto_depIdxs = nil
}
