// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: proto/atom.proto

package atom

import (
	metadata "github.com/minkezhang/bene-api/proto/go/atom/metadata"
	enums "github.com/minkezhang/bene-api/proto/go/enums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Title struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title        string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Localization string `protobuf:"bytes,2,opt,name=localization,proto3" json:"localization,omitempty"`
}

func (x *Title) Reset() {
	*x = Title{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_atom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_proto_atom_proto_rawDescGZIP(), []int{0}
}

func (x *Title) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Title) GetLocalization() string {
	if x != nil {
		return x.Localization
	}
	return ""
}

type Atom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       enums.Type `protobuf:"varint,1,opt,name=type,proto3,enum=bene.enums.Type" json:"type,omitempty"`
	Api        enums.API  `protobuf:"varint,2,opt,name=api,proto3,enum=bene.enums.API" json:"api,omitempty"`
	Id         string     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	PreviewUrl string     `protobuf:"bytes,4,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	Score      int32      `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	// Types that are assignable to Metadata:
	//	*Atom_MetadataEmpty
	//	*Atom_MetadataTv
	Metadata isAtom_Metadata `protobuf_oneof:"metadata"`
}

func (x *Atom) Reset() {
	*x = Atom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_atom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Atom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Atom) ProtoMessage() {}

func (x *Atom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Atom.ProtoReflect.Descriptor instead.
func (*Atom) Descriptor() ([]byte, []int) {
	return file_proto_atom_proto_rawDescGZIP(), []int{1}
}

func (x *Atom) GetType() enums.Type {
	if x != nil {
		return x.Type
	}
	return enums.Type(0)
}

func (x *Atom) GetApi() enums.API {
	if x != nil {
		return x.Api
	}
	return enums.API(0)
}

func (x *Atom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Atom) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *Atom) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (m *Atom) GetMetadata() isAtom_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (x *Atom) GetMetadataEmpty() *metadata.Empty {
	if x, ok := x.GetMetadata().(*Atom_MetadataEmpty); ok {
		return x.MetadataEmpty
	}
	return nil
}

func (x *Atom) GetMetadataTv() *metadata.TV {
	if x, ok := x.GetMetadata().(*Atom_MetadataTv); ok {
		return x.MetadataTv
	}
	return nil
}

type isAtom_Metadata interface {
	isAtom_Metadata()
}

type Atom_MetadataEmpty struct {
	MetadataEmpty *metadata.Empty `protobuf:"bytes,100,opt,name=metadata_empty,json=metadataEmpty,proto3,oneof"`
}

type Atom_MetadataTv struct {
	MetadataTv *metadata.TV `protobuf:"bytes,101,opt,name=metadata_tv,json=metadataTv,proto3,oneof"`
}

func (*Atom_MetadataEmpty) isAtom_Metadata() {}

func (*Atom_MetadataTv) isAtom_Metadata() {}

var File_proto_atom_proto protoreflect.FileDescriptor

var file_proto_atom_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x62, 0x65, 0x6e, 0x65, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x1a, 0x11, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa1, 0x02, 0x0a, 0x04, 0x41,
	0x74, 0x6f, 0x6d, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x62, 0x65, 0x6e, 0x65, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x61, 0x70, 0x69,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x62, 0x65, 0x6e, 0x65, 0x2e, 0x65, 0x6e,
	0x75, 0x6d, 0x73, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x65,
	0x6e, 0x65, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x0d, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x74, 0x76, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62,
	0x65, 0x6e, 0x65, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x54, 0x56, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x54, 0x76, 0x42, 0x0a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x42, 0x2e,
	0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6e,
	0x6b, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2f, 0x62, 0x65, 0x6e, 0x65, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x74, 0x6f, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_atom_proto_rawDescOnce sync.Once
	file_proto_atom_proto_rawDescData = file_proto_atom_proto_rawDesc
)

func file_proto_atom_proto_rawDescGZIP() []byte {
	file_proto_atom_proto_rawDescOnce.Do(func() {
		file_proto_atom_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_atom_proto_rawDescData)
	})
	return file_proto_atom_proto_rawDescData
}

var file_proto_atom_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_atom_proto_goTypes = []interface{}{
	(*Title)(nil),          // 0: bene.atom.Title
	(*Atom)(nil),           // 1: bene.atom.Atom
	(enums.Type)(0),        // 2: bene.enums.Type
	(enums.API)(0),         // 3: bene.enums.API
	(*metadata.Empty)(nil), // 4: bene.atom.metadata.Empty
	(*metadata.TV)(nil),    // 5: bene.atom.metadata.TV
}
var file_proto_atom_proto_depIdxs = []int32{
	2, // 0: bene.atom.Atom.type:type_name -> bene.enums.Type
	3, // 1: bene.atom.Atom.api:type_name -> bene.enums.API
	4, // 2: bene.atom.Atom.metadata_empty:type_name -> bene.atom.metadata.Empty
	5, // 3: bene.atom.Atom.metadata_tv:type_name -> bene.atom.metadata.TV
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_atom_proto_init() }
func file_proto_atom_proto_init() {
	if File_proto_atom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_atom_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Title); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_atom_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Atom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_atom_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Atom_MetadataEmpty)(nil),
		(*Atom_MetadataTv)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_atom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_atom_proto_goTypes,
		DependencyIndexes: file_proto_atom_proto_depIdxs,
		MessageInfos:      file_proto_atom_proto_msgTypes,
	}.Build()
	File_proto_atom_proto = out.File
	file_proto_atom_proto_rawDesc = nil
	file_proto_atom_proto_goTypes = nil
	file_proto_atom_proto_depIdxs = nil
}
