// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/atom.proto

package atom

import (
	metadata "github.com/minkezhang/bene-api/proto/go/atom/metadata"
	enums "github.com/minkezhang/bene-api/proto/go/enums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Title struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Localization  string                 `protobuf:"bytes,2,opt,name=localization,proto3" json:"localization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_proto_atom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_proto_atom_proto_rawDescGZIP(), []int{0}
}

func (x *Title) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Title) GetLocalization() string {
	if x != nil {
		return x.Localization
	}
	return ""
}

type Atom struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Type       enums.Type             `protobuf:"varint,1,opt,name=type,proto3,enum=bene.enums.Type" json:"type,omitempty"`
	Api        enums.API              `protobuf:"varint,2,opt,name=api,proto3,enum=bene.enums.API" json:"api,omitempty"`
	Titles     []*Title               `protobuf:"bytes,3,rep,name=titles,proto3" json:"titles,omitempty"`
	Id         string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	PreviewUrl string                 `protobuf:"bytes,5,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	Score      int64                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	Synopsis   string                 `protobuf:"bytes,7,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	// Types that are valid to be assigned to Metadata:
	//
	//	*Atom_MetadataEmpty
	//	*Atom_MetadataTv
	//	*Atom_MetadataMovie
	Metadata      isAtom_Metadata `protobuf_oneof:"metadata"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Atom) Reset() {
	*x = Atom{}
	mi := &file_proto_atom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Atom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Atom) ProtoMessage() {}

func (x *Atom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Atom.ProtoReflect.Descriptor instead.
func (*Atom) Descriptor() ([]byte, []int) {
	return file_proto_atom_proto_rawDescGZIP(), []int{1}
}

func (x *Atom) GetType() enums.Type {
	if x != nil {
		return x.Type
	}
	return enums.Type(0)
}

func (x *Atom) GetApi() enums.API {
	if x != nil {
		return x.Api
	}
	return enums.API(0)
}

func (x *Atom) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *Atom) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Atom) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *Atom) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Atom) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *Atom) GetMetadata() isAtom_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Atom) GetMetadataEmpty() *metadata.Empty {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataEmpty); ok {
			return x.MetadataEmpty
		}
	}
	return nil
}

func (x *Atom) GetMetadataTv() *metadata.TV {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataTv); ok {
			return x.MetadataTv
		}
	}
	return nil
}

func (x *Atom) GetMetadataMovie() *metadata.Movie {
	if x != nil {
		if x, ok := x.Metadata.(*Atom_MetadataMovie); ok {
			return x.MetadataMovie
		}
	}
	return nil
}

type isAtom_Metadata interface {
	isAtom_Metadata()
}

type Atom_MetadataEmpty struct {
	MetadataEmpty *metadata.Empty `protobuf:"bytes,100,opt,name=metadata_empty,json=metadataEmpty,proto3,oneof"`
}

type Atom_MetadataTv struct {
	MetadataTv *metadata.TV `protobuf:"bytes,101,opt,name=metadata_tv,json=metadataTv,proto3,oneof"`
}

type Atom_MetadataMovie struct {
	MetadataMovie *metadata.Movie `protobuf:"bytes,102,opt,name=metadata_movie,json=metadataMovie,proto3,oneof"`
}

func (*Atom_MetadataEmpty) isAtom_Metadata() {}

func (*Atom_MetadataTv) isAtom_Metadata() {}

func (*Atom_MetadataMovie) isAtom_Metadata() {}

var File_proto_atom_proto protoreflect.FileDescriptor

const file_proto_atom_proto_rawDesc = "" +
	"\n" +
	"\x10proto/atom.proto\x12\tbene.atom\x1a\x11proto/enums.proto\x1a\x14proto/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\x05Title\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\"\n" +
	"\flocalization\x18\x02 \x01(\tR\flocalization\"\xab\x03\n" +
	"\x04Atom\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.bene.enums.TypeR\x04type\x12!\n" +
	"\x03api\x18\x02 \x01(\x0e2\x0f.bene.enums.APIR\x03api\x12(\n" +
	"\x06titles\x18\x03 \x03(\v2\x10.bene.atom.TitleR\x06titles\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x1f\n" +
	"\vpreview_url\x18\x05 \x01(\tR\n" +
	"previewUrl\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x03R\x05score\x12\x1a\n" +
	"\bsynopsis\x18\a \x01(\tR\bsynopsis\x12B\n" +
	"\x0emetadata_empty\x18d \x01(\v2\x19.bene.atom.metadata.EmptyH\x00R\rmetadataEmpty\x129\n" +
	"\vmetadata_tv\x18e \x01(\v2\x16.bene.atom.metadata.TVH\x00R\n" +
	"metadataTv\x12B\n" +
	"\x0emetadata_movie\x18f \x01(\v2\x19.bene.atom.metadata.MovieH\x00R\rmetadataMovieB\n" +
	"\n" +
	"\bmetadataB.Z,github.com/minkezhang/bene-api/proto/go/atomb\x06proto3"

var (
	file_proto_atom_proto_rawDescOnce sync.Once
	file_proto_atom_proto_rawDescData []byte
)

func file_proto_atom_proto_rawDescGZIP() []byte {
	file_proto_atom_proto_rawDescOnce.Do(func() {
		file_proto_atom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_atom_proto_rawDesc), len(file_proto_atom_proto_rawDesc)))
	})
	return file_proto_atom_proto_rawDescData
}

var file_proto_atom_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_atom_proto_goTypes = []any{
	(*Title)(nil),          // 0: bene.atom.Title
	(*Atom)(nil),           // 1: bene.atom.Atom
	(enums.Type)(0),        // 2: bene.enums.Type
	(enums.API)(0),         // 3: bene.enums.API
	(*metadata.Empty)(nil), // 4: bene.atom.metadata.Empty
	(*metadata.TV)(nil),    // 5: bene.atom.metadata.TV
	(*metadata.Movie)(nil), // 6: bene.atom.metadata.Movie
}
var file_proto_atom_proto_depIdxs = []int32{
	2, // 0: bene.atom.Atom.type:type_name -> bene.enums.Type
	3, // 1: bene.atom.Atom.api:type_name -> bene.enums.API
	0, // 2: bene.atom.Atom.titles:type_name -> bene.atom.Title
	4, // 3: bene.atom.Atom.metadata_empty:type_name -> bene.atom.metadata.Empty
	5, // 4: bene.atom.Atom.metadata_tv:type_name -> bene.atom.metadata.TV
	6, // 5: bene.atom.Atom.metadata_movie:type_name -> bene.atom.metadata.Movie
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_atom_proto_init() }
func file_proto_atom_proto_init() {
	if File_proto_atom_proto != nil {
		return
	}
	file_proto_atom_proto_msgTypes[1].OneofWrappers = []any{
		(*Atom_MetadataEmpty)(nil),
		(*Atom_MetadataTv)(nil),
		(*Atom_MetadataMovie)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_atom_proto_rawDesc), len(file_proto_atom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_atom_proto_goTypes,
		DependencyIndexes: file_proto_atom_proto_depIdxs,
		MessageInfos:      file_proto_atom_proto_msgTypes,
	}.Build()
	File_proto_atom_proto = out.File
	file_proto_atom_proto_goTypes = nil
	file_proto_atom_proto_depIdxs = nil
}
